name: Angular Linting (Develop)

on:
  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint Angular Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can change this to the desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      run: npm run lint
