name: Angular Linting (Develop)

on:
  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint Angular Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # You can change this to the desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      run: npm run lint

  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /var/www/html/chat.edu.frontend &&
              git checkout develop &&
              git fetch --all &&
              git reset --hard origin/develop &&
              git pull origin develop &&
              sudo npm i &&
              sudo npm run build'