name: Angular Linting (Develop)

on:
  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint Angular Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # You can change this to the desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Run Linting
      run: npm run lint

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 13.234.180.165 >> ~/.ssh/known_hosts

    - name: Deploy code to EC2
      run: |
        ssh ubuntu@13.234.180.165 'cd /var/www/html/chat.edu.frontend && git pull && npm run build'